### PR TITLE
[New Workflow] Adds Configuration Backup Workflow Pattern

### PR DESCRIPTION
**Pull request by ShehryarAbbasi**
*Issue #, if available:* [337](https://github.com/aws-samples/step-functions-workflows-collection/issues/337)

*Description of changes:*
Adds a new Workflow which can discover and centrally store Resource configurations as a point-in-time snapshot in a mult-region, multi-account setting using an existing AWS Config Aggregator. This solution uses SAM and leverages AWS SDK integrations to provide a low-code example of interacting with AWS Config and Amazon S3 APIs.

- Shows how to Paginate for List APIs using `NextToken` when using AWS SDK integrations
- Shows how to add dynamic partitioning in S3 using `Intrinsic Functions`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bls20AWS** [comment]
Please include a .png export of the workflow image (transparent , without annotations)

**Comment by ShehryarAbbasi** [comment]
@bls20AWS Changed image to be the export from the workflow (PNG, transparent, without annotations)

**Comment by ShehryarAbbasi** [comment]
Made some minor updates to the `example-workflow.json` to fix the repoURL and templateDir values

**Comment by bls20AWS** [comment]
merged

**Pull request merged**
