### PR TITLE
adding distributed-map-csv-iterator-tf workflow

### PR DESCRIPTION
**Pull request by aboushad**
*Issue #, if available:*

*Description of changes: Adding distributed-map-csv-iterator-tf workflow using Terraform

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bls20AWS** [comment]
please at a valid example-workflow.json

**Comment by aboushad** [comment]
Hey Ben, workflow is under statemachines/statemachine.asl.json
This is the same structure I normally use, let me know if you need a modified structure

**Comment by bls20AWS** [comment]
the example-workflow.json is the metadata file about the workflow. Use this as a template: https://github.com/aws-samples/step-functions-workflows-collection/blob/main/_workflow_model/example-workflow.json

**Comment by aboushad** [comment]
Done added example-workflow.json

**Pull request merged**
